# Site settings
title: The Needy Today
header-img: img/home-bg.jpg
email: theneedytoday@gmail.com
description: "The Needy Today a place, in Makeni Sierra Leone for needy and deprived people."
baseurl: "/theneedytoday"
url: "http://jacobburenstam.com"
facebook_username: tnt.sierraleone

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
